# Generated by Django 2.1.4 on 2019-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_usertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='payid',
            field=models.ForeignKey(default=1, on_delete='do_nothing', to='bankapp.UserPayMethod'),
            preserve_default=False,
        ),
    ]
